services:
  - type: web
    name: benefit-questionnaire
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_with_pdf:app --bind 0.0.0.0:$PORT
    healthCheckPath: /
    autoDeploy: true
